/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,js,vue}"],
  theme: {
    extend: {
      // Define new colours
      colors: {
        bakerloo: "#B36305",
        central: "#E32017",
        circle: "#FFD300",
        district: "#00782A",
        elizabeth: "#9364CD",
        "hammersmith-city": "#F3A9BB",
        jubilee: "#A0A5A9",
        metropolitan: "#9B0056",
        northern: "#000000",
        piccadilly: "#003688",
        victoria: "#0098D4",
        "waterloo-city": "#95CDBA",
        dlr: "#00A4A7",
        "tfl-rail": "#0019A8",
        overground: "#EE7C0E",
        "london-overground": "#EE7C0E",
        tram: "#7AC943",
        "emirates-cable-car": "#E21836",
      },
    },
  },
  plugins: [],
  safelist: [
    "bg-bakerloo", 
    "bg-central",
    "bg-circle",
    "bg-district",
    "bg-elizabeth",
    "bg-hammersmith-city",
    "bg-jubilee",
    "bg-metropolitan",
    "bg-northern",
    "bg-piccadilly",
    "bg-victoria",
    "bg-waterloo-city",
    "bg-dlr",
    "bg-tfl-rail",
    "bg-overground",
    "bg-london-overground",
    "bg-tram",
    "bg-emirates-cable-car",
    "border-bakerloo",
    "border-central",
    "border-circle",
    "border-district",
    "border-elizabeth",
    "border-hammersmith-city",
    "border-jubilee",
    "border-metropolitan",
    "border-northern",
    "border-piccadilly",
    "border-victoria",
    "border-waterloo-city",
    "border-dlr",
    "border-tfl-rail",
    "border-overground",
    "border-london-overground",
    "border-tram",
    "border-emirates-cable-car",
  ],
};